run all checks against pyquil, but still fail the job i

diff --git a/.github/workflows/msrv.yml b/.github/workflows/msrv.yml
--- a/.github/workflows/msrv.yml
+++ b/.github/workflows/msrv.yml
@@ -96,12 +96,15 @@ jobs:
         run: |
           set -o pipefail
           pip uninstall -y -r <(pip freeze) || true
-          pip install "./pyquil[latex]" maturin mypy ruff pytest
+          pip install "./pyquil[latex]" maturin mypy ruff pytest pytest-mock
           maturin develop -m quil-rs/quil-py/Cargo.toml
           cd pyquil
           mypy pyquil
           ruff check pyquil
           pytest test/unit -x
+      - name: Fail job if Check changes against pyQuil failed
+        if: steps.check_pyquil.outcome == 'failure'
+        run: exit 1  # This will mark the job as failed
 
   fmt:
     name: Rustfmt
